In [1]:
import torch
from torch.autograd import Variable

In [2]:
x = torch.randn(3, requires_grad=True)
print(x)

tensor([2.3236, 0.1875, 1.2236], requires_grad=True)


In [3]:
y = x+2
print(y)

tensor([4.3236, 2.1875, 3.2236], grad_fn=<AddBackward0>)


In [4]:
z = y*y*2
print(z)

tensor([37.3871,  9.5704, 20.7834], grad_fn=<MulBackward0>)


In [5]:
z = z.mean()
print(z)

tensor(22.5803, grad_fn=<MeanBackward0>)


In [6]:
z.backward() #dz/dx
print(x.grad)

tensor([5.7648, 2.9167, 4.2982])
