In [2]:
import torch

In [3]:
y = torch.randn(1,2,3,4,5)

In [4]:
y

tensor([[[[[-0.4282,  0.4043, -0.9953, -0.2275, -0.1200],
           [ 2.6781, -0.8968,  0.4485,  0.1502,  0.8516],
           [-0.1083,  1.3658,  0.8352,  1.1738, -0.1001],
           [ 1.5774, -1.8878,  0.4312,  0.0223,  0.2824]],

          [[-1.2293,  1.9760,  0.4780,  0.6657, -0.5549],
           [-0.9505,  0.2913, -0.5655,  2.5966,  0.5871],
           [ 0.3739,  0.4964, -0.4747,  0.1672,  0.1898],
           [ 0.8763,  0.4812,  0.7825, -1.7117, -0.4068]],

          [[ 0.1461, -0.4601,  1.4377,  0.6058,  1.3637],
           [ 0.1906,  1.3104,  0.7365, -0.5459,  1.4490],
           [ 0.8056, -1.2001, -0.3611, -0.4439,  0.9365],
           [ 0.3555, -2.1266,  0.4892, -1.1445, -0.2398]]],


         [[[ 1.0539, -2.0284,  0.2636,  1.2923,  0.0606],
           [-1.1127,  2.3315,  1.5068, -0.5791, -0.1083],
           [-0.6148,  0.5422, -0.6424,  0.4080, -2.8211],
           [ 0.1479,  0.5152, -1.5036, -0.1921, -0.1605]],

          [[ 1.1691, -0.1385,  1.9223,  0.7965, -0.4338],
    

In [5]:
y = torch.zeros(4,4)
y

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [6]:
x = [34,23,78,44,23]


In [7]:
import numpy as np
x1 = np.array(x)
x1

array([34, 23, 78, 44, 23])

In [8]:
torch.from_numpy(x1)

tensor([34, 23, 78, 44, 23])

In [9]:
y = torch.randn(2,2)

In [10]:
torch.exp(y)

tensor([[0.9703, 0.6790],
        [1.0825, 0.9171]])

In [11]:
torch.manual_seed(1234)
torch.randn(4,4)

tensor([[-0.1117, -0.4966,  0.1631, -0.8817],
        [ 0.0539,  0.6684, -0.0597, -0.4675],
        [-0.2153,  0.8840, -0.7584, -0.3689],
        [-0.3424, -1.4020,  0.3206, -1.0219]])

In [12]:
torch.Tensor(4,4).uniform_(0,1)

tensor([[0.2837, 0.6567, 0.2388, 0.7313],
        [0.6012, 0.3043, 0.2548, 0.6294],
        [0.9665, 0.7399, 0.4517, 0.4757],
        [0.7842, 0.1525, 0.6662, 0.3343]])

In [13]:
if torch.cuda.is_available():
    device = torch.device('cuda')
    x = torch.ones(5, device=device)
    y=torch.ones(5)
    y = y.to(device)
    z = x + y
    z = z.to("cpu")