In [1]:
import torch

In [4]:
x = torch.arange(4, dtype=torch.float32)
x

tensor([0., 1., 2., 3.])

In [5]:
x.requires_grad_(True)
x.grad

In [6]:
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [7]:
y.backward()

In [8]:
y

tensor(28., grad_fn=<MulBackward0>)

In [9]:
x.grad

tensor([ 0.,  4.,  8., 12.])

In [12]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])