In [1]:
import torch

In [8]:
x = torch.arange(12,dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [9]:
x.numel()

12

In [10]:
x.shape

torch.Size([12])

In [12]:
X = x.reshape(3,4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [14]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [15]:
torch.ones(3,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
a = torch.randn(3,4)
a

tensor([[ 0.5994, -0.3236,  2.0871,  0.1323],
        [ 0.2190, -0.5079,  0.4488,  0.8035],
        [-0.3908, -0.9105,  0.0432,  0.0062]])

In [18]:
A= a.reshape(12)
A

tensor([ 0.5994, -0.3236,  2.0871,  0.1323,  0.2190, -0.5079,  0.4488,  0.8035,
        -0.3908, -0.9105,  0.0432,  0.0062])

In [19]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [20]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [21]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [22]:
X[0]

tensor([0., 1., 2., 3.])

In [23]:
X[1:1]

tensor([], size=(0, 4))

In [24]:
X[1:2]

tensor([[4., 5., 6., 7.]])

In [25]:
X[1:]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [26]:
X[:2]

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [27]:
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [28]:
X[1,2] = 17
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [29]:
Y=X
Y

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5., 17.,  7.],
        [ 8.,  9., 10., 11.]])

In [30]:
X[:2,:] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [31]:
Y[:,:2] = 11
Y

tensor([[11., 11., 12., 12.],
        [11., 11., 12., 12.],
        [11., 11., 10., 11.]])

In [32]:
X

tensor([[11., 11., 12., 12.],
        [11., 11., 12., 12.],
        [11., 11., 10., 11.]])

In [33]:
Y

tensor([[11., 11., 12., 12.],
        [11., 11., 12., 12.],
        [11., 11., 10., 11.]])

In [34]:
x

tensor([11., 11., 12., 12., 11., 11., 12., 12., 11., 11., 10., 11.])

In [35]:
torch.exp(x)

tensor([ 59874.1406,  59874.1406, 162754.7969, 162754.7969,  59874.1406,
         59874.1406, 162754.7969, 162754.7969,  59874.1406,  59874.1406,
         22026.4648,  59874.1406])

In [36]:
x = torch.tensor([1.0,2,4,5])
y = torch.tensor([2,-3,3,1])
x+y, x-y, x*y, x/y

(tensor([ 3., -1.,  7.,  6.]),
 tensor([-1.,  5.,  1.,  4.]),
 tensor([ 2., -6., 12.,  5.]),
 tensor([ 0.5000, -0.6667,  1.3333,  5.0000]))

In [39]:
X= torch.arange(12, dtype=torch.int32).reshape(3,4)
Y = torch.randn(3,4)
X,Y

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]], dtype=torch.int32),
 tensor([[ 0.2870, -0.4672,  1.4019, -0.5033],
         [-0.2660, -1.2060,  1.1764,  0.8578],
         [ 1.2653, -0.2343, -0.5046, -1.1464]]))

In [40]:
torch.cat((X,Y), dim=0), torch.cat((X,Y), dim=1)

(tensor([[ 0.0000,  1.0000,  2.0000,  3.0000],
         [ 4.0000,  5.0000,  6.0000,  7.0000],
         [ 8.0000,  9.0000, 10.0000, 11.0000],
         [ 0.2870, -0.4672,  1.4019, -0.5033],
         [-0.2660, -1.2060,  1.1764,  0.8578],
         [ 1.2653, -0.2343, -0.5046, -1.1464]]),
 tensor([[ 0.0000,  1.0000,  2.0000,  3.0000,  0.2870, -0.4672,  1.4019, -0.5033],
         [ 4.0000,  5.0000,  6.0000,  7.0000, -0.2660, -1.2060,  1.1764,  0.8578],
         [ 8.0000,  9.0000, 10.0000, 11.0000,  1.2653, -0.2343, -0.5046, -1.1464]]))

In [41]:
X==Y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

Broadcasting

In [42]:
a = torch.arange(3, dtype=torch.float32).reshape(3,1)
b = torch.arange(2, dtype=torch.float32).reshape(1,2)
a,b

(tensor([[0.],
         [1.],
         [2.]]),
 tensor([[0., 1.]]))

In [44]:
a+b,a*b

(tensor([[0., 1.],
         [1., 2.],
         [2., 3.]]),
 tensor([[0., 0.],
         [0., 1.],
         [0., 2.]]))